name: Deploy ai-processor to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  job_compute_diff:
    name: Compute file diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3
      - name: Compute diff
        uses: dorny/paths-filter@v2
        id: compute_diff
        with:
          filters: |
            files:
              - 'title-generator/**'
              - '.github/workflows/ci-ai-processor.yml'
    outputs:
      files: ${{ steps.compute_diff.outputs.files }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [job_compute_diff]
    if: ${{ needs.job_compute_diff.outputs.files == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          ECR_REPOSITORY: cotuber-consumer/ai-processor
          IMAGE_TAG: latest
        run: |
          docker build -t cotuber-consumer/ai-processor:latest ai-processor
          docker tag cotuber-consumer/ai-processor:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Logout from Amazon ECR
        run: docker logout ${{ steps.ecr-login.outputs.registry }}
